### ISSUE TITLE
checklist so i don't forget anything

### ISSUE THREAD

**Issue by Maccraft123** [Maccraft123/prawn-packages#1]
- [ ] xonotic
- [ ] box86 from git as qemu-armhf-static replacement(binfmt)
- [ ] daemon
- [ ] hantro libva, ffmpeg and more
- [ ] mono with https://github.com/mono/corert/pull/33
- [ ] mojoshader
- [ ] mesa with https://gitlab.freedesktop.org/snippets/1147/raw
